#!/bin/bash
#
# Prepares the "stack" to run apps and the environment to run buildpacks
#

apt-get update

# Common tools
apt-get install -y curl
apt-get install -y git
apt-get install -y mercurial
apt-get install -y ruby1.9.1-dev

# Common database clients/libs
apt-get install -y mysql-client

# Other common libraries
apt-get install -y libssl0.9.8
apt-get install -y nodejs
apt-get install -y wget git-core libfontconfig1-dev

cd /usr/local/share
wget https://phantomjs.googlecode.com/files/phantomjs-1.9.0-linux-x86_64.tar.bz2
tar xjf phantomjs-1.9.0-linux-x86_64
ln -s /usr/local/share/phantomjs-1.9.0-linux-x86_64/bin/phantomjs /usr/local/share/phantomjs; ln -s /usr/local/share/phantomjs-1.9.0-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs; ln -s /usr/local/share/phantomjs-1.9.0-linux-x86_64/bin/phantomjs /usr/bin/phantomjs

git clone git://github.com/n1k0/casperjs.git
cd casperjs
git checkout tags/1.0.2
ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs

# Buildpack dependencies:

# Ruby
apt-get install -y rubygems
update-alternatives --set ruby /usr/bin/ruby1.9.1
update-alternatives --set gem /usr/bin/gem1.9.1
gem install bundler
cd /build/buildpacks/heroku-buildpack-ruby && bundle install


